In [1]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [2]:
X_train = [
    [3.393533211,2.331273381],
    [3.110073483,1.781539638],
    [1.343808831,3.368360954],
    [3.582294042,4.679179110],
    [2.280362439,2.866990263],
    [7.423436942,4.696522875],
    [5.745051997,3.533989803],
    [9.172168622,2.511101045],
    [7.792783481,3.424088941],
    [7.939820817,0.791637231]
]
y_train = [0,0,0,0,0,1,1,1,1,1]

In [3]:
X_train = np.array(X_train)
y_train = np.array(y_train)

In [4]:
x_test = np.array([2.093607318,3.365731514])

In [5]:
X_test = x_test.reshape(1, -1)
X_test.shape

(1, 2)

In [6]:
x_test.shape

(2,)

In [7]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [8]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [9]:
kNN_classifier.predict(X_test)

array([0])

In [11]:
%run kNN/kNN.py

In [14]:
kNN_Classifier = kNNClassifier(6)

In [15]:
kNN_Classifier.fit(X_train, y_train)

kNN(K=6)

In [16]:
kNN_Classifier.predict(X_test)

array([0])

In [19]:
X_test = np.array([[2.093607318,3.365731514], [8,3.365731514]])
X_test.shape

(2, 2)

In [20]:
kNN_Classifier.predict(X_test)

array([0, 1])