In [1]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 666)

In [4]:
standard_scaler = StandardScaler()

In [5]:
standard_scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
standard_scaler.mean_

array([ 5.83416667,  3.0825    ,  3.70916667,  1.16916667])

In [7]:
standard_scaler.scale_

array([ 0.81019502,  0.44076874,  1.76295187,  0.75429833])

In [8]:
X_train_standard = standard_scaler.transform(X_train)
X_test_standard = standard_scaler.transform(X_test)

In [9]:
np.mean(X_train_standard[:, 0])

1.3026616822268502e-15

In [10]:
np.std(X_train_standard[:, 0])

1.0000000000000002

In [11]:
knn_cls = KNeighborsClassifier(n_neighbors=3)
knn_cls.fit(X_train_standard, y_train)
knn_cls.score(X_test_standard, y_test)

1.0

In [12]:
knn_cls.score(X_test, y_test)

0.33333333333333331

In [13]:
from playML.preprocessing import StandardScaler

In [14]:
standard_scaler = StandardScaler()
standard_scaler.fit(X_train)

In [15]:
standard_scaler.mean_

array([ 5.83416667,  3.0825    ,  3.70916667,  1.16916667])

In [16]:
standard_scaler.scale_

array([ 0.81019502,  0.44076874,  1.76295187,  0.75429833])

In [17]:
X_train_standard = standard_scaler.transform(X_train)
X_test_standard = standard_scaler.transform(X_test)

In [18]:
knn_cls = KNeighborsClassifier(n_neighbors=3)
knn_cls.fit(X_train_standard, y_train)
knn_cls.score(X_test_standard, y_test)

1.0

In [19]:
knn_cls.score(X_test, y_test)

0.33333333333333331