# Numpy基础

In [1]:
import numpy as np

In [2]:
import sys
print(sys.version)

3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]


In [3]:
np.__version__

'1.13.1'

### Python List的特点 使用灵活 不要求每个元素的数据类型一致 影响了性能

In [4]:
L = [i for i in range(10)]

In [7]:
L[5] = 'haha'
L

[0, 1, 2, 3, 4, 'haha', 6, 7, 8, 9]

### array.array 每个元素的数据类型必须一致 灵活性较低

In [8]:
import array

arr = array.array('i',[i for i in range(10)])

In [9]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [10]:
arr[5] = 'huhaha'

TypeError: an integer is required (got type str)

## numpy.array 所有元素必须是同一类型

In [12]:
nparr = np.array([i for i in range(10)])
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [13]:
nparr[5] = 'haha'

ValueError: invalid literal for int() with base 10: 'haha'

In [15]:
nparr.dtype

dtype('int32')

In [16]:
nparr[3] = 5.0
nparr

array([  0,   1,   2,   5,   4, 100,   6,   7,   8,   9])

In [19]:
nparr[6] = False
nparr

array([  0,   1,   2,   5,   4, 100,   0,   7,   8,   9])

In [20]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

### 其他创建numpy.array的方法

In [23]:
nparr = np.zeros(10)
nparr

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
nparr.dtype

dtype('float64')

In [25]:
nparr = np.zeros((3, 4), dtype=int)
nparr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
nparr.shape

(3, 4)

In [27]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.full((3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange 步长支持小数

In [30]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [33]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
[i for i in range(0, 10, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
np.arange(0, 10, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

### linspace

In [36]:
np.linspace(0, 20, 10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [37]:
np.linspace(0, 20, 11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

### random

In [39]:
np.random.randint(0, 10)

5

In [40]:
np.random.randint(0, 10, size=10)

array([6, 3, 2, 8, 6, 7, 8, 0, 7, 2])

In [42]:
np.random.randint(0, 10, size=(3, 5))

array([[3, 5, 0, 4, 4],
       [0, 2, 7, 3, 9],
       [8, 6, 0, 7, 1]])

In [278]:
# np.random.seed(666) #随机种子
np.random.randint(0, 10, size=(3, 5))

array([[1, 5, 7, 2, 1],
       [0, 0, 3, 8, 0],
       [8, 7, 8, 9, 6]])

In [55]:
np.random.random() #0-1之间

0.7315955468480113

In [56]:
np.random.random((3, 5))

array([[ 0.8578588 ,  0.76741234,  0.95323137,  0.29097383,  0.84778197],
       [ 0.3497619 ,  0.92389692,  0.29489453,  0.52438061,  0.94253896],
       [ 0.07473949,  0.27646251,  0.4675855 ,  0.31581532,  0.39016259]])

In [57]:
np.random.normal() #均值是0 方差为1的随机数

0.9047266176428719

In [58]:
np.random.normal(100, 10, size=(3, 5))

array([[  91.73716735,  108.21013692,  103.67125916,  116.53995858,
         101.39464726],
       [  87.8284645 ,   90.05052633,   84.35514135,   83.71209956,
         112.31748656],
       [  90.86399664,   97.29155933,  114.20249136,   90.17735611,
         108.09764984]])

In [62]:
#查询函数使用文档
np.random.normal?

In [63]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

### 05Numpy.array的基本操作

In [64]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [66]:
x.ndim

1

In [67]:
X.ndim

2

In [68]:
x.shape

(10,)

In [69]:
X.shape

(3, 5)

In [70]:
x.size

10

In [71]:
X.size

15

### numpy.array的数据访问

In [72]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x[5]

5

In [74]:
X[0,4]

4

In [75]:
x[:5:2]

array([0, 2, 4])

In [76]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
X[:, 2]

array([ 2,  7, 12])

In [79]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [80]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [82]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [84]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [85]:
X #对于numpy来说，为了提高效率，取子矩阵相当于引用，修改会影响原矩阵 可用copy进行复制

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [86]:
subX = X[:2, :3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [87]:
subX[0, 0] = 0
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [88]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [89]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [90]:
x.reshape(5, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### 合并操作

In [91]:
a = np.arange(1, 4, 1)
a

array([1, 2, 3])

In [92]:
b = np.arange(3, 0, -1)
b

array([3, 2, 1])

In [93]:
c = np.array([666, 666, 666])
c

array([666, 666, 666])

In [96]:
x = np.concatenate([a, b, c]) #对多个数组进行合并
x

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [97]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

x = np.concatenate([a, a])
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [98]:
x = np.concatenate([a, a], axis = 1)
x

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [99]:
x = np.concatenate([a, c]) #concatenate只能处理维数一样的矩阵或向量

ValueError: all the input arrays must have same number of dimensions

In [100]:
x = np.concatenate([a, c.reshape(1, -1)])
x

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

### vstack(vertical)竖直的拼接  hstack(horizontal)水平的拼接

In [101]:
x = np.vstack([a, c]) #不要求维度一致
x

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [103]:
d = np.full((2, 2), fill_value = 100)
d.ndim
d.shape

(2, 2)

In [104]:
x = np.hstack([a, d])
x

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 数组的分割 split vsplit(竖直的分割) hsplit(水平的分割)

In [106]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
a1, a2, a3 = np.split(a, [3, 7])

In [108]:
a1

array([0, 1, 2])

In [109]:
a2

array([3, 4, 5, 6])

In [110]:
a3

array([7, 8, 9])

In [112]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
A1, A2 = np.split(A, [2])

In [114]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [115]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
A1, A2 = np.split(A, [2], axis=1)

In [117]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [118]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [123]:
upper, lower = np.vsplit(A, [2])

In [124]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [125]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
left, right = np.hsplit(A, [2])

In [128]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [129]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [131]:
np.hstack([left, right])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [132]:
np.vstack([lower, upper])

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [134]:
x = np.arange(16).reshape(4, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
X, y = np.hsplit(x, [-1])

In [137]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [138]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [141]:
y.shape

(4,)

In [145]:
y.ndim

1

In [147]:
y.reshape(-1, 1)[:, 0]

array([ 3,  7, 11, 15])

### numpy.array中的运算

In [148]:
n = 100000
L = [i for i in range(n)]

In [149]:
%%time
A = [2*e for e in L]

Wall time: 16 ms


In [158]:
L = np.arange(n)

In [178]:
%%time
A = np.array(2*e for e in L)

Wall time: 0 ns


In [187]:
%%time
A = 2 * L

Wall time: 997 µs


In [188]:
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

### Universal Function

In [190]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [191]:
x + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [192]:
x - 1

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [193]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [194]:
x / 2

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ]])

In [195]:
x // 2

array([[0, 0, 1, 1, 2],
       [2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7]], dtype=int32)

In [196]:
x ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [197]:
x % 2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]], dtype=int32)

In [198]:
1 / x

D:\ProgramData\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111],
       [ 0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857]])

In [199]:
np.abs(x)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [200]:
np.sin(x)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

In [203]:
x = np.arange(1, 17).reshape(4, 4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [204]:
np.log(x)

array([[ 0.        ,  0.69314718,  1.09861229,  1.38629436],
       [ 1.60943791,  1.79175947,  1.94591015,  2.07944154],
       [ 2.19722458,  2.30258509,  2.39789527,  2.48490665],
       [ 2.56494936,  2.63905733,  2.7080502 ,  2.77258872]])

In [205]:
np.exp(x)

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
          5.45981500e+01],
       [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
          2.98095799e+03],
       [  8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
          1.62754791e+05],
       [  4.42413392e+05,   1.20260428e+06,   3.26901737e+06,
          8.88611052e+06]])

In [206]:
np.power(3, x)

array([[       3,        9,       27,       81],
       [     243,      729,     2187,     6561],
       [   19683,    59049,   177147,   531441],
       [ 1594323,  4782969, 14348907, 43046721]], dtype=int32)

In [207]:
3 ** x

array([[       3,        9,       27,       81],
       [     243,      729,     2187,     6561],
       [   19683,    59049,   177147,   531441],
       [ 1594323,  4782969, 14348907, 43046721]], dtype=int32)

In [208]:
np.log2(x)

array([[ 0.        ,  1.        ,  1.5849625 ,  2.        ],
       [ 2.32192809,  2.5849625 ,  2.80735492,  3.        ],
       [ 3.169925  ,  3.32192809,  3.45943162,  3.5849625 ],
       [ 3.70043972,  3.80735492,  3.9068906 ,  4.        ]])

In [209]:
np.log10(x)

array([[ 0.        ,  0.30103   ,  0.47712125,  0.60205999],
       [ 0.69897   ,  0.77815125,  0.84509804,  0.90308999],
       [ 0.95424251,  1.        ,  1.04139269,  1.07918125],
       [ 1.11394335,  1.14612804,  1.17609126,  1.20411998]])

### 矩阵运算 保证两个矩阵之间shape相同

In [210]:
A = np.arange(4).reshape(2, -1)
A

array([[0, 1],
       [2, 3]])

In [211]:
B = np.full((2, 2), fill_value=10)
B

array([[10, 10],
       [10, 10]])

In [212]:
A + B

array([[10, 11],
       [12, 13]])

In [213]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [214]:
A * B

array([[ 0, 10],
       [20, 30]])

In [215]:
A / B

array([[ 0. ,  0.1],
       [ 0.2,  0.3]])

In [216]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [217]:
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [218]:
v = np.arange(2)
v

array([0, 1])

In [219]:
v + A

array([[0, 2],
       [2, 4]])

In [224]:
np.vstack([v]*A.shape[0])

array([[0, 1],
       [0, 1]])

In [226]:
np.tile(v, (2, 1)) #矩阵堆叠 在x方向堆叠两次 在y方向堆叠一次

array([[0, 1],
       [0, 1]])

In [227]:
v * A

array([[0, 1],
       [0, 3]])

In [228]:
v.dot(A)

array([2, 3])

In [229]:
A.dot(v) #numpy在运算时会自动决定是将向量取为列向量还是行向量

array([1, 3])

### 矩阵的逆矩阵 只有对方阵才能求逆矩阵

In [230]:
A = np.arange(1, 5).reshape(2, -1)
A

array([[1, 2],
       [3, 4]])

In [231]:
invA = np.linalg.inv(A)
invA

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [232]:
A.dot(invA)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [233]:
invA.dot(A)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

### 非方阵可以求伪逆矩阵

In [237]:
B = np.arange(16).reshape(2, -1)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [238]:
invB = np.linalg.inv(B)

LinAlgError: Last 2 dimensions of the array must be square

In [239]:
pinvB = np.linalg.pinv(B)
pinvB

array([[ -1.35416667e-01,   5.20833333e-02],
       [ -1.01190476e-01,   4.16666667e-02],
       [ -6.69642857e-02,   3.12500000e-02],
       [ -3.27380952e-02,   2.08333333e-02],
       [  1.48809524e-03,   1.04166667e-02],
       [  3.57142857e-02,   8.67361738e-18],
       [  6.99404762e-02,  -1.04166667e-02],
       [  1.04166667e-01,  -2.08333333e-02]])

In [240]:
B.dot(pinvB)

array([[  1.00000000e+00,  -9.71445147e-17],
       [ -1.33226763e-15,   1.00000000e+00]])

In [241]:
pinvB.dot(B)

array([[  4.16666667e-01,   3.33333333e-01,   2.50000000e-01,
          1.66666667e-01,   8.33333333e-02,   4.57966998e-16,
         -8.33333333e-02,  -1.66666667e-01],
       [  3.33333333e-01,   2.73809524e-01,   2.14285714e-01,
          1.54761905e-01,   9.52380952e-02,   3.57142857e-02,
         -2.38095238e-02,  -8.33333333e-02],
       [  2.50000000e-01,   2.14285714e-01,   1.78571429e-01,
          1.42857143e-01,   1.07142857e-01,   7.14285714e-02,
          3.57142857e-02,   4.16333634e-17],
       [  1.66666667e-01,   1.54761905e-01,   1.42857143e-01,
          1.30952381e-01,   1.19047619e-01,   1.07142857e-01,
          9.52380952e-02,   8.33333333e-02],
       [  8.33333333e-02,   9.52380952e-02,   1.07142857e-01,
          1.19047619e-01,   1.30952381e-01,   1.42857143e-01,
          1.54761905e-01,   1.66666667e-01],
       [  6.93889390e-17,   3.57142857e-02,   7.14285714e-02,
          1.07142857e-01,   1.42857143e-01,   1.78571429e-01,
          2.14285714e-01,   2.5

### 聚合操作

In [243]:
a = np.random.random((2, 2))
a

array([[ 0.57773404,  0.89274848],
       [ 0.12138544,  0.66083873]])

In [246]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

179 ms ± 5.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.92 ms ± 534 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [247]:
np.min(big_array)

1.8276329760702481e-06

In [248]:
np.max(big_array)

0.99999937480102941

In [250]:
A = np.arange(16).reshape(4, -1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [251]:
np.sum(A)

120

In [252]:
np.sum(A, axis=0) #沿着行进行，求每列的和

array([24, 28, 32, 36])

In [253]:
np.sum(A, axis=1) #沿着列进行，求每行的和

array([ 6, 22, 38, 54])

In [254]:
np.prod(A) #求乘积

0

In [255]:
np.prod(A + 1)

2004189184

In [256]:
np.mean(A) #对于一些和样本差距较大的点比较敏感

7.5

In [257]:
np.median(A) #可以更好的描述样本

7.5

In [258]:
np.percentile(big_array, q=50)

0.5004396669647766

In [259]:
np.median(big_array)

0.5004396669647766

In [261]:
for q in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=q))

1.82763297607e-06
0.249990840509
0.500439666965
0.750053533537
0.999999374801


In [262]:
np.max(big_array)

0.99999937480102941

In [263]:
np.var(big_array) #方差

0.083416180515766561

In [264]:
np.std(big_array) #标准差

0.28881859447716757

In [266]:
x = np.random.normal(0, 1, size=100)

In [267]:
np.mean(x)

0.025112038881886685

In [268]:
np.var(x)

1.1571048620944824

In [280]:
# np.random.seed(666)
x = np.random.normal(0, 1, size=100)
np.mean(x)

-0.10776262893981473

### 索引 argment运算

In [281]:
np.min(big_array)

1.8276329760702481e-06

In [282]:
np.argmin(big_array)

841430

In [283]:
big_array[841430]

1.8276329760702481e-06

In [284]:
np.max(big_array)

0.99999937480102941

In [285]:
np.argmax(big_array)

869889

In [286]:
big_array[869889]

0.99999937480102941

### 排序和使用索引

In [288]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [290]:
np.random.shuffle(x)
x

array([13,  5,  2,  3, 14,  4,  1, 10, 11,  8,  0,  9,  7, 15, 12,  6])

In [291]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [292]:
y = np.random.randint(10, size=(4, 4))
y

array([[5, 7, 1, 4],
       [4, 7, 2, 6],
       [3, 2, 5, 1],
       [1, 7, 7, 0]])

In [293]:
np.sort(y) #默认是沿着列的方向，对每一行进行排序

array([[1, 4, 5, 7],
       [2, 4, 6, 7],
       [1, 2, 3, 5],
       [0, 1, 7, 7]])

In [294]:
np.sort(y, axis=0)

array([[1, 2, 1, 0],
       [3, 7, 2, 1],
       [4, 7, 5, 4],
       [5, 7, 7, 6]])

In [295]:
x

array([13,  5,  2,  3, 14,  4,  1, 10, 11,  8,  0,  9,  7, 15, 12,  6])

In [296]:
np.argsort(x) #排序后的元素的索引值 也可对矩阵进行排序

array([10,  6,  2,  3,  5,  1, 15, 12,  9, 11,  7,  8, 14,  0,  4, 13], dtype=int64)

In [298]:
np.partition(x, 8) #快排的标定点 数据是无须的

array([ 5,  0,  2,  3,  6,  4,  1,  7,  8,  9, 10, 11, 14, 15, 12, 13])

In [299]:
x[np.argsort(x)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [301]:
np.argpartition(x, 8) #根据标定点进行快排得到的元素索引，无序存在的

array([ 1, 10,  2,  3, 15,  5,  6, 12,  9, 11,  7,  8,  4, 13, 14,  0], dtype=int64)

In [302]:
np.sort(y)

array([[1, 4, 5, 7],
       [2, 4, 6, 7],
       [1, 2, 3, 5],
       [0, 1, 7, 7]])

In [303]:
y

array([[5, 7, 1, 4],
       [4, 7, 2, 6],
       [3, 2, 5, 1],
       [1, 7, 7, 0]])

In [304]:
np.argsort(y)

array([[2, 3, 0, 1],
       [2, 0, 3, 1],
       [3, 1, 0, 2],
       [3, 0, 1, 2]], dtype=int64)

In [306]:
np.argsort(y, axis=0)

array([[3, 2, 0, 3],
       [2, 0, 1, 2],
       [1, 1, 2, 0],
       [0, 3, 3, 1]], dtype=int64)

In [307]:
np.sort(y, axis=0)

array([[1, 2, 1, 0],
       [3, 7, 2, 1],
       [4, 7, 5, 4],
       [5, 7, 7, 6]])

In [310]:
np.partition(y, 2)

array([[1, 4, 5, 7],
       [2, 4, 6, 7],
       [1, 2, 3, 5],
       [0, 1, 7, 7]])