In [2]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
x[[3, 9, 12]]

array([ 3,  9, 12])

In [7]:
ind = np.array([
    [0, 5],
    [7, 9]
])
x[ind]

array([[0, 5],
       [7, 9]])

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [11]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
X[::2, col]

array([[ 1,  2,  3],
       [ 9, 10, 11]])

In [14]:
col = [True, False, True, False]
X[1:3, col]

array([[ 4,  6],
       [ 8, 10]])

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### numpy.array的比较

In [16]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [17]:
np.sum(x > 3)

12

In [18]:
np.count_nonzero(x < 3) #统计非0的值

3

In [19]:
np.any(x == 0) #有一个为True的则为True

True

In [20]:
np.any(x != 0)

True

In [21]:
np.any(x < 0)

False

In [23]:
np.all(x > 0) #全部为True才为True

False

In [24]:
np.all(x >= 0)

True

In [26]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.sum(X >0, axis = 1)

array([3, 4, 4, 4])

In [28]:
np.sum(X%2 == 0, axis=0)

array([4, 0, 4, 0])

In [29]:
np.sum((x>3) & (x<6)) #位运算符不是条件运算符 与

2

In [30]:
np.sum((x>3) | (x > 10)) #或

12

In [35]:
np.sum(~(x==5)) #非

15

In [36]:
X[X[:,3]%3==0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [37]:
X[:, 3]%3==0

array([ True, False, False,  True], dtype=bool)

### 首先使用pandas对数据进行预处理，再将预处理之后的数据转换为numpy的矩阵，送给机器学习的算法，sklearn中的算法接受的是一个numpy格式的矩阵